parameters:

    twitter_stream_ids:
        - 1096369709430255617

    stream_url: ws://127.0.0.1:3535

services:

    app:
        class: Feeder\App
        arguments: ['@feed.manager']

    feed.manager:
        class: Feeder\Manager\FeedManager
        calls:
            - [addFeedAdapter, ['@feed.twitter_stream_adapter']]

    feed.twitter_stream_handler_listener:
        class: Feeder\Listener\FeedHandlerStreamerListener
        arguments: ['@app.serializer', '@app.parameterBag']
        lazy:  true

    feed.tweet_assembler:
      class: Feeder\Service\TweetAssembler
      lazy:  true

    feed.twitter_stream:
        class: Feeder\Service\UserTwitterStreamProcessor
        arguments: ['@symfony.event_dispatcher', '@feed.tweet_assembler', '@app.parameterBag', '%twitter_stream_ids%']
        lazy:  true

    feed.twitter_stream_adapter:
        class: Feeder\Adapter\TwitterStreamAdapter
        arguments: ['@feed.twitter_stream']
        lazy:  true

    feed.stream_server:
        class: Feeder\Service\FeedServer

    symfony.event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

